[build]
  publish = "build"
  command = "dotnet publish -c Release -f net8.0-windows10.0.19041.0 -o build"

[context.production.environment]
  DOTNET_ROOT = "/opt/buildhome/.dotnet"
  PATH = "/opt/buildhome/.dotnet:/opt/buildhome/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
